### ISSUE TITLE
Bug: Fix clickable characters on home screen

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/smashmate#16]
#### Desired Behavior

The app should show a Fighter's data only if a character card is directly clicked on 
#### Actual Behavior

The app will show a Fighter's data if you click near the character card
#### Steps to Reproduce

> ##### To trigger the bug, you must ...

Click anywhere near the left or right of a character card while on the home screen 
## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.
- [ ] In main.js change it so the click listener is on `div.character-card` instead of `div.card-column`
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
