### ISSUE TITLE
Feature: User can create an account

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/smashmate#34]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create their own account
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Inside the navbar will be a button that says `create account`. When clicked, the user will be directed to the account creation page where they can input a username and password to create an account. Alternatively, trying to favorite a fighter will bring up a modal asking the user if they want to create an account or cancel.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Install all necessary packages
- [ ] Create a `server` directory
  - [ ] Within the `server` directory, create a `db` directory with a `conn.ts` file for connecting to the MongoDb database
  - [ ] Create a `routes` directory
  - [ ] Create a `server.ts` file
- [ ] Make sure new users and their hashed passwords are being added to the database
- [ ] Make sure an error is thrown and the user is notified if their username is taken
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a `registration` page
- [ ] Create a `register` component
### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
