### ISSUE TITLE
Refactor: Integrate deeper objects into application

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/smashmate#41]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.
- [ ] Change `fighterArray` and `favorites` into a deeper object data structure like the wireframe below

- [x] Functions to change in `RenderCards.tsx`:
  - [x] `handleFavoriting`
  - [x] `handleHearts`
  - [x] `handleShowDetails`
  - [x] `homeOrFavorites`
  - [x] variable `allCards`
- [x] Functions to change in `App.tsx`:
  - [x] `fetchFighters`
- [ ] Functions to change in `FighterDetails`:
  - [x] handleCheckTitle
  - [x] fetchTitle
  - [x] binarySearcher
- [x] Change `.length` to `.size`:
  - [x] `FavoritesList`
  - [x] `App.tsx`
  - [x] `App.test.tsx`
  - [x] `RenderCards`
  - [x] `favoritingSlice`
  - [x] `Favorites`
  - [x] 3 in `FighterDetails`
- [x] Change favorites sorting to only happen when `Favorites` component is rendered
- [x] Change `favoritingSlice`  and `fighterArraySlice`
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.

## 🏛️ Wireframe

![image](https://user-images.githubusercontent.com/90172283/202830586-d73a5c88-c6ce-44b8-adec-d081653d903f.png)
