### ISSUE TITLE
Feature: User can Search for Characters

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/smashmate#44]
User can search for characters

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click onto a search icon to open a searchbar. They can then type into the searchbar to filter characters of their choosing.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add a searchbar icon to the `RenderCards` component
  - [x] Find icon on FontAwesome
  - [x] Place in the top center of the page
  - [x] Scrolling down should cause it to turn translucent
- [x] Create a `Searchbar.tsx` component
  - [x] Clicking on the search icon should render the component
  - [x] The searchbar should automatically be focused
- [x] Create an `Overlay.tsx` component
  - [x] Clicking on the search icon should render the component
  - [x] Clicking on the overlay should unmount Searchbar and Overlay component
- [x] Create a `Searchbar.test.tsx` component and in it add:
  - [x] A test for toggling search icon and searchbar/overlay
  - [x] A test for allowing `enter` to close the searchbar/overlay
  - [x] A test for checking if searchbar is correctly filtering character cards on user input
  - [x] A test for previous user input staying in the searchbar after it closes
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
